### PR TITLE
CPLAT-15693: Fix browser aggregation when used with build filters

### PR DESCRIPTION
**Pull request by evanweible-wf**
# [CPLAT-15693](https://jira.atl.workiva.net/browse/CPLAT-15693)
Issue Status

- Updated dependencies to work on 2.7 and 2.13
- Used `$package$` instead of `$test$`, which will always be an input
(even if build filters are used)

## Testing
- From the `example/project/` directory on Dart 2.7:
  - [ ] Note that using build filters when browser aggregation is enabled currently fails:
    - Check out the `master` branch
    - Run `pub upgrade`
    - Run `pub run build_runner test --build-filter="test/unit/no_html_test**" -- test/unit/no_html_test.dart`
    - Should see the following error:

    ```
    Error on line 6, column 10 of dart_test.yaml: Cannot open file, path = './test/dart_test.browser_aggregate.yaml' (OS Error: No such file or directory, errno = 2)
      ╷
    6 │ include: test/dart_test.browser_aggregate.yaml
      │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ╵
    ```
  - [ ] Verify that this branch fixes that issue:
    - Checkout this `fix_build_filters_with_browser_aggregation` branch
    - Reset your working tree - make sure that the `dart_test.browser_aggregate.yaml` file isn't deleted
    - Run `pub upgrade`
    - Run `pub run build_runner test --build-filter="test/unit/no_html_test**" -- test/unit/no_html_test.dart`
    - Verify that it passes

### CODE REVIEW

**Review by robbecker-wf — DISMISSED** [review]

**Review by kirkrichardson-wk — DISMISSED** [review]
QA +1

**Review by kirkrichardson-wk — APPROVED** [review]
QA +1

**Comment by evanweible-wf** [comment]
@Workiva/release-management-p

**Review by todbachman-wf — APPROVED** [review]

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
