### PR TITLE
FEDX-434 : Complete test_html_builder GHA migration

### PR DESCRIPTION
**Pull request by alishadalal-wk**
Ensure that the `gha-upload-test-reports` is called, even if it is without a test report, but preferably with. Then we can remove the **Dockerfile** and **skynet.yaml**.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by nickshoust-wf** [comment]
@alishadalal-wk @emmajelley-wk Is this able to be completed now ?
I see on the ticket https://jira.atl.workiva.net/browse/FEDX-434 
>Closed the PR https://github.com/Workiva/test_html_builder/pull/45 as per conversation: https://workiva.slack.com/archives/C04L911LA5B/p1699388226557279?thread_ts=1699383002.054569&cid=C04L911LA5B 

But i dont have access to that slack channel to see the reason why it was closed

**Comment by nickshoust-wf** [comment]
@alishadalal-wk @andrewgianikas-wk  Is this able to be completed now ?
I see on the ticket https://jira.atl.workiva.net/browse/FEDX-434 
>Closed the PR https://github.com/Workiva/test_html_builder/pull/45 as per conversation: https://workiva.slack.com/archives/C04L911LA5B/p1699388226557279?thread_ts=1699383002.054569&cid=C04L911LA5B 

But i dont have access to that slack channel to see the reason why it was closed

**Comment by alishadalal-wk** [comment]
> @alishadalal-wk @andrewgianikas-wk Is this able to be completed now ? I see on the ticket https://jira.atl.workiva.net/browse/FEDX-434
> 
> > Closed the PR #45 as per conversation: https://workiva.slack.com/archives/C04L911LA5B/p1699388226557279?thread_ts=1699383002.054569&cid=C04L911LA5B
> 
> But i dont have access to that slack channel to see the reason why it was closed

**Conversation** - For OSS repos we apparently need to keep workiva-build webhooks enabled and run a Dockerfile build that just runs dart pub get and an empty skynet config for now: https://workiva.slack.com/archives/CDYB01HT7/p1699382676952339?thread_ts=1699285866.306659&cid=CDYB01HT7
because of this I think we'll want to close https://github.com/Workiva/test_html_builder/pull/45 for now. We can re-open it later when RM figures out what to do for OSS repos

**Pull request closed without merging**
